package com.example.unilink.activities

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.View
import android.view.animation.AnimationUtils
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import androidx.lifecycle.lifecycleScope
import com.example.unilink.R
import com.example.unilink.databinding.ActivityLoginBinding
import com.example.unilink.models.User
import com.example.unilink.repository.UserRepository
import com.example.unilink.utils.HapticUtils
import com.example.unilink.utils.LocationHelper
import com.example.unilink.utils.ThemeUtils
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.launch

class LoginActivity : AppCompatActivity() {

    private lateinit var binding: ActivityLoginBinding
    private val auth = FirebaseAuth.getInstance()
    private val userRepository = UserRepository()
    private lateinit var credentialManager: CredentialManager

    override fun onCreate(savedInstanceState: Bundle?) {
        try { ThemeUtils.applyTheme(this) } catch (e: Exception) {}
        super.onCreate(savedInstanceState)
        binding = ActivityLoginBinding.inflate(layoutInflater)
        setContentView(binding.root)

        credentialManager = CredentialManager.create(this)

        binding.btnGoogleLogin.setOnClickListener {
            HapticUtils.playSelection(it)
            signInWithGoogle()
        }

        runEntryAnimations()
    }

    private fun runEntryAnimations() {
        val slideUp = AnimationUtils.loadAnimation(this, R.anim.slide_in_up)
        val fadeIn = AnimationUtils.loadAnimation(this, android.R.anim.fade_in)
        
        binding.llBranding.startAnimation(fadeIn)
        binding.loginCard.startAnimation(slideUp)
        binding.tvLegal.startAnimation(fadeIn)
        
        // Pulse logo for attention
        val pulse = AnimationUtils.loadAnimation(this, R.anim.pulse)
        binding.cvLogo.startAnimation(pulse)
    }

    private fun signInWithGoogle() {
        // Use default_web_client_id generated by Google Services plugin
        val webClientId = try {
            getString(R.string.default_web_client_id)
        } catch (e: Exception) {
            Log.e("LoginActivity", "Failed to load default_web_client_id. Falling back to hardcoded ID.")
            "326237133092-g8lqf9d2dbv4epoo9ofma5ubp04dqm33.apps.googleusercontent.com"
        }
        
        Log.d("LoginActivity", "Using Web Client ID: $webClientId")

        val googleIdOption: GetGoogleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId)
            .setAutoSelectEnabled(false) // Set to false to force account picker for testing
            .build()

        val request: GetCredentialRequest = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        lifecycleScope.launch {
            try {
                showLoading(true, "Launching Secure Gateway...")
                val result = credentialManager.getCredential(
                    request = request,
                    context = this@LoginActivity,
                )
                val credential = result.credential
                
                Log.d("LoginActivity", "Received credential type: ${credential.type}")

                try {
                    // Modern way to extract Google ID Token
                    val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                    showLoading(true, "Authenticating with Firebase...")
                    val googleIdToken = googleIdTokenCredential.idToken
                    
                    if (googleIdToken.isNullOrEmpty()) {
                        throw Exception("Google ID Token is empty")
                    }

                    val firebaseCredential = GoogleAuthProvider.getCredential(googleIdToken, null)
                    
                    auth.signInWithCredential(firebaseCredential)
                        .addOnCompleteListener { task ->
                            if (task.isSuccessful) {
                                handleUserSync()
                            } else {
                                showLoading(false)
                                val exception = task.exception
                                val msg = if (exception?.message?.contains("App Check", ignoreCase = true) == true) {
                                    "Security check failed. Please register your debug token in Firebase Console."
                                } else {
                                    "Firebase Auth Error: ${exception?.localizedMessage}"
                                }
                                Log.e("LoginActivity", "Firebase Auth Failed", exception)
                                Toast.makeText(this@LoginActivity, msg, Toast.LENGTH_LONG).show()
                            }
                        }
                } catch (e: Exception) {
                    showLoading(false)
                    Log.e("LoginActivity", "Failed to parse Google ID Token: ${e.message}")
                    Toast.makeText(this@LoginActivity, "Credential mismatch or parsing error", Toast.LENGTH_SHORT).show()
                }
            } catch (e: GetCredentialException) {
                showLoading(false)
                val errorMsg = when (e) {
                    is androidx.credentials.exceptions.GetCredentialCancellationException -> "Sign-in cancelled"
                    is androidx.credentials.exceptions.GetCredentialInterruptedException -> "Sign-in interrupted"
                    is androidx.credentials.exceptions.GetCredentialProviderConfigurationException -> "Configuration error. Check SHA-1."
                    else -> "Sign-in error: ${e.message}"
                }
                Log.e("LoginActivity", "Google Sign-in Error: $errorMsg", e)
                Toast.makeText(this@LoginActivity, errorMsg, Toast.LENGTH_SHORT).show()
            } catch (e: Exception) {
                showLoading(false)
                Log.e("LoginActivity", "General Error", e)
                Toast.makeText(this@LoginActivity, "Failed: ${e.message}", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun handleUserSync() {
        showLoading(true, "Syncing Campus Profile...")
        val user = auth.currentUser ?: return
        val uid = user.uid
        val name = user.displayName ?: ""
        val email = user.email ?: ""
        val profilePic = user.photoUrl?.toString()

        Log.d("LoginActivity", "Auth successful for $uid, fetching location...")

        // Non-blocking location fetch with a timeout fallback
        var locationProcessed = false
        
        val onLocationResult: (Double?, Double?, String?, String?) -> Unit = { lat, lng, city, state ->
            if (!locationProcessed) {
                locationProcessed = true
                Log.d("LoginActivity", "Location result received. lat: $lat, city: $city")
                saveUserData(uid, name, email, profilePic, lat, lng, city, state)
            }
        }

        // 1. Try to get location
        try {
            LocationHelper.getLastLocation(this, onLocationResult)
        } catch (e: Exception) {
            Log.e("LoginActivity", "Location helper crashed", e)
            onLocationResult(null, null, null, null)
        }

        // 2. Safety Timeout: If location takes more than 3.5 seconds, proceed without it
        binding.root.postDelayed({
            if (!locationProcessed) {
                Log.w("LoginActivity", "Location fetch timed out, proceeding with defaults")
                onLocationResult(null, null, null, null)
            }
        }, 3500)
    }

    private fun saveUserData(uid: String, name: String, email: String, profilePic: String?, lat: Double?, lng: Double?, city: String?, state: String?) {
        userRepository.getUserById(uid) { existingUser ->
            if (existingUser == null) {
                val newUser = User(
                    uid = uid,
                    name = name,
                    email = email,
                    profileImageUrl = profilePic,
                    latitude = lat,
                    longitude = lng,
                    city = city ?: "",
                    state = state ?: ""
                )
                userRepository.saveUser(newUser) {
                    showLoading(false)
                    startActivity(Intent(this@LoginActivity, ProfileSetupActivity::class.java))
                    finish()
                }
            } else {
                existingUser.latitude = lat ?: existingUser.latitude
                existingUser.longitude = lng ?: existingUser.longitude
                if (existingUser.profileImageUrl == null) existingUser.profileImageUrl = profilePic
                
                userRepository.saveUser(existingUser) {
                    showLoading(false)
                    navigateToMain()
                }
            }
        }
    }

    private fun showLoading(show: Boolean, status: String = "Syncing...") {
        binding.loadingOverlay.visibility = if (show) View.VISIBLE else View.GONE
        binding.tvLoadingStatus.text = status
        if (show) {
            binding.loadingOverlay.alpha = 0f
            binding.loadingOverlay.animate().alpha(1f).setDuration(300).start()
        }
    }

    private fun navigateToMain() {
        startActivity(Intent(this, MainActivity::class.java))
        finish()
    }
}
